### ISSUE TITLE
你好，我想问一下您当时处理json时是怎么做的，涉及大量递归会内存溢出

### ISSUE THREAD

**Issue by ranchoy** [shizhao1100/zhihu-topicTree-visualization#1]

**Comment by sz-p** [comment]
你好，回想我当时做这个项目的时候也是抓取的含有id和pid的数据条目，基于python，采取传统递归的操作方式生成包含children字段的JSON数据。当时并没有发生内存溢出。
有两种可能：
1、	我当时抓取数据不完全缺失十分严重。
2、	我机器性能较好，能吃下的数据更多。
不过还可能有意料之外的情况导致内存溢出例如：
1、	数据条目内部包含错误，导致递归存在死循环。
2、	程序本身包含错误。
最终：
很高兴有人会对我以前做过的一些小小的程序感兴趣，也由衷的祝愿你在Coding和Debug中能收获更多，如果必要的话，可以把程序及数据开源至Github，问题定位或许会更加方便
